import { DataGridCustomStyle } from "@/app/_components/styled";
import {
  Column,
  ColumnChooser,
  ColumnFixing,
  Editing,
  Item,
  LoadPanel,
  Paging,
  Scrolling,
  SearchPanel,
  Toolbar,
} from "devextreme-react/data-grid";

export const DividendTable = (props: any) => {
  const RenderValue = (rowData: any) => {
    return "$" + rowData.displayValue;
  };
  return (
    <DataGridCustomStyle
      id="gridContainer"
      dataSource={props.data}
      columnAutoWidth={true}
      keyExpr="year"
      allowColumnReordering={true}
      showBorders={false}
      showRowLines={true}
      showColumnLines={false}
      height={400}
    >
      <Column
        dataField="year"
        caption="Year"
        minWidth={100}
        alignment="center"
        fixed={true}
      />
      <Column
        dataField="jan"
        caption="January"
        minWidth={100}
        alignment="center"
        cellRender={RenderValue}
      />
      <Column
        dataField="feb"
        caption="February"
        minWidth={100}
        alignment="center"
        cellRender={RenderValue}
      />
      <Column
        dataField="mar"
        caption="March"
        minWidth={100}
        alignment="center"
        cellRender={RenderValue}
      />
      <Column
        dataField="apr"
        caption="April"
        minWidth={100}
        alignment="center"
        cellRender={RenderValue}
      />
      <Column
        dataField="may"
        caption="May"
        minWidth={100}
        alignment="center"
        cellRender={RenderValue}
      />
      <Column
        dataField="jun"
        caption="June"
        minWidth={100}
        alignment="center"
        cellRender={RenderValue}
      />
      <Column
        dataField="jul"
        caption="July"
        minWidth={100}
        alignment="center"
        cellRender={RenderValue}
      />
      <Column
        dataField="aug"
        caption="August"
        minWidth={100}
        alignment="center"
        cellRender={RenderValue}
      />
      <Column
        dataField="sep"
        caption="September"
        minWidth={100}
        alignment="center"
        cellRender={RenderValue}
      />
      <Column
        dataField="oct"
        caption="October"
        minWidth={100}
        alignment="center"
        cellRender={RenderValue}
      />
      <Column
        dataField="nov"
        caption="November"
        minWidth={100}
        alignment="center"
        cellRender={RenderValue}
      />
      <Column
        dataField="dec"
        caption="December"
        minWidth={100}
        alignment="center"
        cellRender={RenderValue}
      />
    </DataGridCustomStyle>
  );
};
